#!/usr/bin/env bash
set -e

useradd --uid 10011001 --home-dir /home/hcnet --no-log-init hcnet \
    && mkdir -p /home/hcnet \
    && chown -R hcnet:hcnet /home/hcnet

mkdir -p /opt/hcnet/bin
mkdir -p /opt/hcnet/www
chown -R hcnet:hcnet /opt/hcnet/www
mkdir -p /opt/hcnet/postgresql/data
