name: Aurora master

on:
  push:
    branches: [master]

jobs:

  push-aurora-image-sha:
    name: Push hcnet/aurora:sha to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get image tag (short sha)
        shell: bash
        id: get_tag
        run: echo ::set-output name=TAG::$(git rev-parse --short ${{ github.sha }} )

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          # TODO: Commented out until we disable the CircleCI jobs
          # push: true
          tags: hcnet/aurora:${{ steps.get_tag.outputs.TAG }}
          file: services/aurora/docker/Dockerfile.dev

  push-state-diff-image:
    name: Push hcnet/ledger-state-diff:{sha,latest} to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          push: true
          tags: hcnet/ledger-state-diff:${{ github.sha }},hcnet/ledger-state-diff:latest
          file: exp/tools/dump-ledger-state/Dockerfile
          build-args: GITCOMMIT=${{ github.sha }}
          no-cache: true
